services:
  postgres:
    image: postgres:18
    container_name: ho-setup-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_name
    ports:
      - "5435:5432"
    volumes:
      - ho_setup_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d db_name"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  ho_setup_pgdata:
